apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-k8s-web-final-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Digital_Marketing_Frontend-deployment
  template:
    metadata:
      labels:
        app: Digital_Marketing_Frontend-deployment
    spec:
      containers:
        - name: Digital_Marketing_Frontend
          image: elghibaomar/Digital_Marketing_Frontend:latest
          env:
            - name: PORT
              value: "8082"
          ports:
          - containerPort: 8082


---
apiVersion: v1
kind: Service
metadata:
  name: Digital_Marketing_Frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
  selector:
    app: Digital_Marketing_Frontend-deployment
        


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: vuejs-k8s-web-service
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 8082
#   selector:
#     app: vuejs-k8s-web-deployment







